### ISSUE TITLE
Merge swift-2.0 with master

### ISSUE THREAD

**Issue by papertigers** [honghaoz/Ji#11]
Hey can you merge swift-2.0 branch with master now that iOS 9 and swift 2 dropped.  Carthage currently complains that the 2.0 branch doesn't have a framework scheme.  For now I can just build it manually as a workaround. Thanks!

**Comment by honghaoz** [comment]
Hey @papertigers Now it should work!

**Comment by honghaoz** [comment]
@papertigers As it has been test by myself. This issue could be closed
