### ISSUE TITLE
Does library support concat and another logical operations?

### ISSUE THREAD

**Issue by Arti3DPlayer** [honghaoz/Ji#20]
Have troubles with queries that contains logical operations. They always return empty results.

**Comment by honghaoz** [comment]
Hi @Arti3DPlayer, it should support logical operations, could you please provide an example?

**Comment by Arti3DPlayer** [comment]
For example at this page:

http://www.homedepot.com/p/Arnold-Universal-Snow-Thrower-Key-Set-4-Piece-490-241-0008/202251530?keyword=4902410008

`concat(//*[@id='ajaxPrice']/text(), //*[@id='ciItemPrice']/text())`

```
let jiDoc = Ji(htmlData: responseData)!
                                    let titleNode = jiDoc.xPath(text)
                                    print(titleNode)

```

**Comment by Arti3DPlayer** [comment]
i found the solution i guess. This is because i return string, not dom element :( Is there a solution, how to make it works ?

**Comment by honghaoz** [comment]
@Arti3DPlayer Hey what the solution you found? I tried `concat` and it doesn't work. Not sure whether it's syntax problem or internal problem. I'll continue to figure it out

**Comment by Arti3DPlayer** [comment]
oh, you don't understand me. I mean that i found the issue ) I tried:

https://github.com/tid-kijyun/Kanna
https://github.com/topfunky/hpple

No one is working with strings. My question at stackoverflow: http://stackoverflow.com/questions/33353848/swift-xpath-search-return-string

**Comment by honghaoz** [comment]
Based on libxml2.0 C library, not NSXMLParser.

**Comment by Arti3DPlayer** [comment]
Yes but issue in code :( Because i have tested at Python libxml library, it works
