### ISSUE TITLE
Works fine in simulator, but failed in iphone

### ISSUE THREAD

**Issue by ChadChan1992** [honghaoz/Ji#21]
it worked fine in simulator. 
but when i tried on my phone, it returned nil.
8.0+ version

**Comment by honghaoz** [comment]
Can you provide me more information? Something like what's your code looks like, your html/xml string, xpath query string...

**Comment by ChadChan1992** [comment]
Sorry i found that it return nil on version under iPhone 5s, either real phone or simulator.
but it work fine on other version, so it might not be a big problem.

**Comment by honghaoz** [comment]
I think it's related to 64bit vs. 32bit devices. Thanks for your issue :+1:
