### ISSUE TITLE
有没有方法只解析本级别的content，不解析下级的content

### ISSUE THREAD

**Issue by jiti1000** [honghaoz/Ji#23]
Hi, 晚上好，
在解析时，预想只解析本级别的content，有没有方便的实现办法，
html字符串如下：
![jiissue](https://cloud.githubusercontent.com/assets/11306290/11185584/67ff77e0-8cb8-11e5-8773-c2d9b5af7f4c.png)
代码如下：
let elements = JiDocument.xPath("//a")?.first?.content
调试输出如下：
![3742c6f3-4280-4eeb-87c3-36a349d8d4b8](https://cloud.githubusercontent.com/assets/11306290/11185617/8fa0bd04-8cb8-11e5-94fa-35d3272e8d1d.png)

问题：本次解析时，我只想得到 "新闻" 这个content，不希望下级的2267也解析出来。

新手，请多指教，
感谢！🙏

**Comment by honghaoz** [comment]
@jiti1000 Hi，针对这个问题，有两种办法。
方法一（推荐）：
修改xpath为`//a/text()`

``` swift
let elements = JiDocument.xPath("//a/text()")?.first?.content
```

这样，只有`a`里面的文字会被拿出来，`span`里的东西就被忽略了。

方法二：
可以更改JiNode的`keepTextNode`属性为true

``` swift
JiDocument?.rootNode?.keepTextNode = true
let elements = JiDocument.xPath("//a/text()")?.first!
print(eles?.children[1].content)
```

然后取到的`a`节点会有两个子节点，一个是`span`节点，另一个是text节点，也就是包含`新闻`字符的节点。

默认情况下，`keepTextNode`是`false`的

**Comment by jiti1000** [comment]
再请教下，需要解析的 字符串中  "//a/text()"
//   和   /   有什么区别？

**Comment by honghaoz** [comment]
@jiti1000 请参考这个 http://www.w3schools.com/xsl/xpath_syntax.asp

**Comment by jiti1000** [comment]
Thanks!
还发现一个使用的问题，不知道是bug还是我使用的问题。
html字符如下：
![1](https://cloud.githubusercontent.com/assets/11306290/11230938/bdeefeec-8dde-11e5-8657-04a2c9e0b0da.png)
程序如下：
JiDocument.xPath("//li/a")?.count
let elements = JiDocument.xPath("//li/a")!

let a = elements[0].rawContent
let b = elements[1].rawContent
let c = elements[2].rawContent

let d = elements[0].xPath("//a/text()").first?.content
let e = elements[1].xPath("//a/text()").first?.content
let f = elements[2].xPath("//a/text()").first?.content

调试输出入下图：
![2](https://cloud.githubusercontent.com/assets/11306290/11230969/173fd430-8ddf-11e5-8400-81a350897575.png)

我预想的是  d="勋章申请区" ,  e="CHH第二届机王争霸赛",  f="大恶魔的Blog"
但是实际d，e，f 都 ＝ "勋章申请区"

我暂时解决办法是把每个element先取rawcontent，然后再转JiDocument, 再xpath一次，感觉这样比较繁琐，帮忙看下是否有方便的办法，感谢

**Comment by honghaoz** [comment]
@jiti1000 你试试吧d,e,f 里的xpath改成`./text()` 看看？还是上面那个连接，`.`是选取当前node的。

**Comment by jiti1000** [comment]
太感谢啦！
