### ISSUE TITLE
My Application is open source which used Ji for html parse

### ISSUE THREAD

**Issue by zixun** [honghaoz/Ji#24]
My Application( [CocoaChina+](https://github.com/zixun/CocoaChinaPlus) ) is open source. It used Ji for html parse.
and some of other swift opensource library,such as : [RxSwift](https://github.com/ReactiveX/RxSwift), [Neon](https://github.com/mamaral/Neon)

Thanks for Ji 😄

**Comment by honghaoz** [comment]
Wow! 太棒了！让我来膜拜膜拜！好好研究下，我也希望可以贡献自己的力量
