### ISSUE TITLE
Re-writing HTML

### ISSUE THREAD

**Issue by ashleymills** [honghaoz/Ji#25]
Hi,

I'd like to use Ji to update tag attributes and re-write the amended HTML. Running a quick test, the updated attributes weren't shown in the updated description. Am I missing something?

Thanks for your work
Ash

**Comment by honghaoz** [comment]
Hey @ashleymills:

Thanks for you issue.

Currently `Ji` is not supporting modifying HTML source. It only for parsing HTML.

I probably should consider put modification in the future plan.
