### ISSUE TITLE
Add support for Xcode 7 / Swift 2

### ISSUE THREAD

**Issue by ghost** [honghaoz/Ji#3]

**Comment by honghaoz** [comment]
Hi, @devnikor, I'll create a branch for Swift 2.0 and will let you know when it's ready.

**Comment by ghost** [comment]
Thanks!

**Comment by honghaoz** [comment]
Hi @devnikor, `swift-2.0` branch is created. The implementation has been test on Xcode7 beta4. Will test it on beta5. You can integrate Ji manually. Thanks :smiley:
