### ISSUE TITLE
tag 1.3.0 Carthage compile error

### ISSUE THREAD

**Issue by atwchiao** [honghaoz/Ji#37]
I tried to compile tag 1.3.0 under macOS 10.12 (16A323) with Carthage 0.18, Xcode 8(8A218a), but get compilation errors.
I am currently using commit "e14bb36" for swift 2.3 development which compiled fine. 
Just wondering any plan to tag another compilable version or a fix for swift 2.3 compatible release?

........................................
prompt $ carthage build Ji --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3
**\* xcodebuild output can be found in /var/folders/hq/kkxg8y3j77v6y6s4lkvhbhm80000gn/T/carthage-xcodebuild.9qOWGh.log
**\* Building scheme "Ji iOS" in Ji.xcworkspace
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    CompileSwift normal armv7
    CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/DerivedSources/Ji_iOS_Tests-Swift.h /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests-Swift.h
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/DerivedSources/Ji_iOS_Tests-Swift.h /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests-Swift.h
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm.swiftmodule /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests.swiftmodule
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm.swiftdoc /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests.swiftdoc
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm64.swiftmodule /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests.swiftmodule
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm64.swiftdoc /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests.swiftdoc
    Ld /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji\ iOS\ Tests normal armv7
    Ld /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji\ iOS\ Tests normal arm64
    CreateUniversalBinary /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest/Ji\ iOS\ Tests normal armv7\ arm64
    GenerateDSYMFile /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest.dSYM /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest/Ji\ iOS\ Tests
(14 failures)
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiNodeXMLTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/htmlXPathTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiNodeHTMLTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/xmlXPathTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiNodeXMLTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/htmlXPathTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/JiNodeHTMLTests.swift:11:18: error: module 'Ji' was not compiled for testing
/Users/username/Documents/project/Carthage/Checkouts/Ji/Tests/xmlXPathTests.swift:11:18: error: module 'Ji' was not compiled for testing
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji iOS Tests.build/Objects-normal/armv7/Ji iOS Tests (No such file or directory)
error: cannot parse the debug map for "/Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji iOS Tests.xctest/Ji iOS Tests": No such file or directory
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/username/Documents/project/Carthage/Checkouts/Ji/Ji.xcworkspace -scheme "Ji iOS" -configuration Release -sdk iphoneos -toolchain com.apple.dt.toolchain.Swift_2_3 ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    CompileSwift normal armv7
    CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/DerivedSources/Ji_iOS_Tests-Swift.h /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests-Swift.h
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/DerivedSources/Ji_iOS_Tests-Swift.h /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests-Swift.h
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm.swiftmodule /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests.swiftmodule
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm.swiftdoc /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji_iOS_Tests.swiftdoc
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm64.swiftmodule /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests.swiftmodule
    Ditto /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji_iOS_Tests.swiftmodule/arm64.swiftdoc /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji_iOS_Tests.swiftdoc
    Ld /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/armv7/Ji\ iOS\ Tests normal armv7
    Ld /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Intermediates/Ji.build/Release-iphoneos/Ji\ iOS\ Tests.build/Objects-normal/arm64/Ji\ iOS\ Tests normal arm64
    CreateUniversalBinary /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest/Ji\ iOS\ Tests normal armv7\ arm64
    GenerateDSYMFile /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest.dSYM /Users/username/Library/Developer/Xcode/DerivedData/Ji-hldoeromjgwrlwckainrykenhdur/Build/Products/Release-iphoneos/Ji\ iOS\ Tests.xctest/Ji\ iOS\ Tests
(14 failures)

**Comment by honghaoz** [comment]
@andykingway Fixed, have a try again?

**Comment by atwchiao** [comment]
Yes, tag 1.3.0 now build fine now with carthage for swift 2.3.
Thank you very much.
