### ISSUE TITLE
Plz Swift Package Manager

### ISSUE THREAD

**Issue by zanezhangzz** [honghaoz/Ji#38]
more and more lib can use by SPM,  Plz

**Comment by honghaoz** [comment]
@FantaZZ Hi, I've considered to support SPM, however currently it's not a easy task. I will update any progress here

**Comment by honghaoz** [comment]
@FantaZZ Hi, Just update to support SPM. Please refer https://github.com/honghaoz/Ji#swift-package-manager-spm to install.
