### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by kiliankoe** [honghaoz/Ji#4]
Hi, I really love this project! Thank you so very much for building it.

Is there a chance though that you could support installing via Carthage as well? Cocoapods is great, no question, but Carthage is pretty cool as well and a staggering amount of great projects already support both giving the users an option of how to integrate with their project.

Thanks for considering 😊

**Comment by honghaoz** [comment]
Hi @kiliankoe Thanks for your support, I'd like to add Carthage support. Since I'm still not very familiar with it, It may take me some time to finish it. Anyway, I'll do it asap. :smiley:

**Comment by kiliankoe** [comment]
Awesome! Great to hear! 

I wanted to create a pull request for this already, as it normally just entails sharing the Xcode scheme, but it seems that the code for Ji isn't built as a framework but as part of an iOS app, which is probably the reason for this to fail. But I'm unfortunately no expert :smiley:

**Comment by honghaoz** [comment]
Cool, feel free to make a PR, we can figure it out why It doesn't work.

**Comment by honghaoz** [comment]
Hey @kiliankoe, I've updated frameworks project and now supports Carthage.
In `Carthfile`, add `github "honghaoz/Ji" >= 1.1.1`.
Let me know whether it works :smile:

**Comment by kiliankoe** [comment]
That's awesome! Thank you so much! :smile: 

I'm just going to go ahead and close this then :wink:
