### ISSUE TITLE
Swift 4, iOS 11, and Xcode 9

### ISSUE THREAD

**Issue by HackShitUp** [honghaoz/Ji#45]
I'm persistently getting the error: 

XPath error : Invalid predicate
XPath error : Invalid expression

During build time for a project on iOS 11, Xcode 9, and Swift 4

**Comment by honghaoz** [comment]
@HackShitUp Thanks for your issue. It's probably from Swift 4, will check the compatibility issue with Swift 4.

**Comment by HackShitUp** [comment]
If you need help (although I don't know how much I can help you haha), feel free to reach out!

**Comment by honghaoz** [comment]
@HackShitUp Hi, I've fixed it in [swift4](https://github.com/honghaoz/Ji/tree/swift4) branch. I will wait until Xcode 9 officially released to publish to `master`.

In the meantime, you could put this into you `Podfile` to use it

```ruby
pod 'Ji', :git=> 'git@github.com:honghaoz/Ji.git', :branch => 'swift4'
```

**Comment by HackShitUp** [comment]
Hi @honghaoz thank you so much for the update! 👍

**Comment by 1000copy** [comment]
I am find the bug too. if you like http otherwise git protocols to github ,may be you like this : 

        pod 'Ji', :git=> 'https://github.com/honghaoz/Ji.git', :branch => 'swift4'

**Comment by the-freshlord** [comment]
@HackShitUp Was switching to the `swift4` branch do the trick? I am having the same problem when using Swift 4. See this issue: #47

**Comment by henry-swe** [comment]
Problem solved after using the branch. @honghaoz Please switch it to `master`.

**Comment by honghaoz** [comment]
@a211212abc Fixed and updated. Thanks
