### ISSUE TITLE
Invalid XPath

### ISSUE THREAD

**Issue by the-freshlord** [honghaoz/Ji#47]
Hello, when using an XPath like this:
```
guard let jiHTML = Ji(htmlString: html) else {
     dispatchGroup.leave()
     return
}
guard let scoreboxNodes = jiHTML.xPath("//div[@class='new-score-box-wrapper']") else {
      dispatchGroup.leave()
      return
}
```
I get an invalid predicate error. The path that i have given is valid. I also tried switching to the `swift4` branch but that didn't work either.

**Comment by the-freshlord** [comment]
#45

**Comment by henry-swe** [comment]
Yes, same problem in Xcode 9

**Comment by honghaoz** [comment]
[Ji 2.1.0](https://github.com/honghaoz/Ji/releases/tag/2.1.0) is up. Should've fixed this problem. Thx
