### ISSUE TITLE
Unable to use Ji on macOS 10.13.4

### ISSUE THREAD

**Issue by gepree** [honghaoz/Ji#50]
macOS 10.13.4
Xcode 9.3

My application uses "honghaoz/Ji" version "2.1.0".

When I compile my application, I get the following error:

Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /Users/[...]/Projects/[...]/Carthage/Build/Mac/Ji.framework/Modules/Ji.swiftmodule/x86_64.swiftmodule

Is there a newer version of "honghaoz/Ji" available that supports Swift 4.1?

Thanks

**Comment by gepree** [comment]
Sorry to comment on my own post, but I found that if I ran the command:

carthage update Ji --platform macOS --no-use-binaries

it worked correctly.  I am not sure if this is a proper fix, so maybe we do need a newer version of Ji that works with Swift 4.1 (macOS 10.13.4, Xcode 9.3)

**Comment by honghaoz** [comment]
Swift now has been upgraded to support Swift 5.0: https://github.com/honghaoz/Ji/tree/5.0.0
