### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by zixun** [honghaoz/Ji#6]
发现一个bug：

```
<div>
  <a href="a1">
    <img src="img1">
  </a>

  <a href="a2">
    <img src="img2">
  </a>

  <a href="a3">
    <img src="img3">
  </a>
</div>
```

通过xPath拿到一个Node列表，然后遍历这个列表，调用每个Node的xPath方法:

```
let nodes = Ji.xPath("//div/a")

for node in nodes {
    let test1 = node.xPath("img")
    let test2 = node.xPath("//img")
}
```

照道理说test2的内容 应该等于test1的，因为现在xPath搜索的环境是node的html中，都只有一个，但是test2把全文的img都检索出来了。

**Comment by honghaoz** [comment]
Hi @zixun 非常感谢你的issue，我觉得这个应该不算bug，如果你测试

``` swift
let nodes = Ji.xPath("//div/a")

for node in nodes {
    let test1 = node.xPath("img")
    let test2 = node.xPath(".//img") // Note: "." selects the current node
}
```

这样得到的结果就只包含一个`img`节点了。

参考：http://www.w3schools.com/xsl/xpath_syntax.asp

> `.`   Selects the current node
> `//book`  Selects all book elements no matter where they are in the document

**Comment by zixun** [comment]
@honghaoz  原来如此。我之前是用 [happle](https://github.com/buloshnikova/happle)来做HTML解析的，这是一个OC的库，不过因为我的工程是用swift2来写的，发现Ji后就果断换到Ji上来了，结果发现同样的代码逻辑，两个库返回的结果不一样，看来是happle库的问题。说实话，你的API设计的比happle赞多了

**Comment by honghaoz** [comment]
@zixun 是的，hpple是一次性把所有的节点信息都parse出来存在了自己dictionary里。我的这个是在libxml上直接的一个wrapper，逻辑有一点区别。anyway，非常感谢你的夸奖，你是阿里巴巴的大神吧 :laughing:

**Comment by zixun** [comment]
@honghaoz 哈哈，我前几天刚从阿里离职，加盟了滴滴

**Comment by honghaoz** [comment]
@zixun 不知道在国内做iOS工作感觉怎么样啊，还没体验过

**Comment by zixun** [comment]
@honghaoz  国内环境没国外好的，你是不是已经肉身翻墙了

**Comment by zixun** [comment]
@honghaoz  我最近在做一个CocoaChina的第三方客户端，直接本地解析HTML的，现在用的就是你的解析库

**Comment by honghaoz** [comment]
@zixun 是啊，肉身翻墙中。能被用上很荣幸啊哈哈
